@extends('layouts.master')

<div id="details_tab">
	<form id="details_tab_form">
				
		<div class="row">
	    <div class="col-3 form-group">
	    	<label for="">Title</label>
	    	<input type="text" class="form-control" value="{{ old('title') ?? $tender->title}}" name="title">
	    </div>
	    <div class="col-3 form-group">
	    	<label for="">Tender No.</label>
	    	<input type="text" placeholder="Autogenerated" readonly="true" value="{{ old('tender_no') ?? $tender->tender_no}}" class="form-control" name="tender_no">
	    </div>
	    <div class="col-3 form-group">
	    	<label for="">Publish date</label>
	    	<input type="text" value="{{ old('publish_date') ?? $tender->publish_date}} "readonly="true" class="form-control datepicker" name="publish_date"/>
	    </div>
	    <div class="col-3 form-group">
	    	<label for="">Reference/Priority No.</label>
	    	<input type="text" value="{{ old('reference_no') ?? $tender->reference_no}} " class="form-control" name="reference_no"/>
	    </div>
	   
	    <div class="col-3 form-group">
	    	<label for="">Total Cost</label>
	    	<input type="text" value="{{ old('total_cost') ?? $tender->total_cost}}" class="form-control" name="total_cost">
	    </div>
	    <div class="col-3 form-group">
	    	<label for="">Document Cost</label>
	    	<input type="text" value="{{ old('document_cost') ?? $tender->document_cost}}" class="form-control" name="document_cost">
	    </div>
	     <div class="col-3 form-group">
	    	<label for="">Place</label>
	    	<input type="text" value="{{ old('place') ?? $tender->place}}" class="form-control" name="place"/>
	    </div>
	    <div class="col-3 form-group">
	    	<label for="">Department</label>
	    	<input type="text" value="{{ old('departm') ?? $tender->departm}}" class="form-control" name="departm"/>
	    </div>
	     <div class="col-3 form-group">
	    	<label for="">Tender fill in Office</label>
	    	<input type="text" value="{{ old('fill_company_office') ?? $tender->fill_company_office}}" name="fill_company_office">
	    </div>	   
	    <div class="w-100"></div>
	    <div class="col-12">
	    	<div class="form-group">
	    		<label for="">Description</label>
	    		<textarea name="descri" class="form-control" id="" cols="30" rows="5">{{ old('descri') ?? $tender->descri}}</textarea>
	    	</div>
	    	<hr>
	    </div>
	    <div class="box-title" style="width: 100%;">
                <div class="col-md-12 m-auto">
                <div class="col-md-12 bg-primary p-2" style="border-radius: 5px;font-size: 17px;
					font-weight: 502;">                	
             		<span>Tender CLIENT Contact</span>
             	</div>	
                    <div class="card">
                        <div class="card-body " >
                            <div class="row">                            	
                                <div class="col-sm-12 col-md-12 col-xl-12" id="mytable1">
                                	<div class="row">
                                		<div class="col-sm-12 col-md-12 col-xl-12 text-center">
                                			<span class="delete_notify"></span>
                                		</div>
                                	</div>
                                	<?php  $count = 1; 
                                	?>
                                	@foreach($client as $clients)

                                	<?php if($count == 1){
                                	 ?>
                                	 	<a style="color:#ffffff ;margin-top:31px" class="btn btn-success pull-right add_button fa fa-plus"></a>
                                	 	<?php if($clients->name != '') { ?>
                                	 		<a delete-id="{{$clients->id }}"  style="color:#ffffff;margin-top:31px" class="delete_reco remove_button fa fa-trash pull-right btn btn-danger"></a>
                                	 		<?php } ?>
                                	 <?php } else{ ?>
                                	 		<a delete-id="{{$clients->id }}" style="color:#ffffff;margin-top:31px" class="delete_reco remove_button fa fa-trash pull-right btn btn-danger"></a>
                                	<?php  } ?>
	                                	<div class="row">                                		
											<div class="col-md-3 col-sm-3 delete_row_{{$clients->id }}">
										    	<div class="form-group">
										    		<label for="">Contact Name</label>
										    		<input type="text" class="form-control" name="contact_name[]" value="{{ $clients->name ?? ''}}"/>
										    	</div>
										    	<input type="hidden" name="update_id[]" value="{{$clients->id}}">
										    </div>
										    <div class="col-md-3 col-sm-3">
										    	<div class="form-group">
										    		<label for="">Email</label>
										    		<input type="text" class="form-control" name="email[]" value="{{ $clients->email }}" />
										    	</div>
										    </div>
										     <div class="col-md-3 col-sm-3">
										    	<div class="form-group">
										    		<label for="">Designation</label>
										    		<input type="text" class="form-control" name="desig[]" value="{{ $clients->desig }}" />
										    	</div>
										    </div>
										     <div class="col-md-3 col-sm-3">
										    	<div class="form-group">
										    		<label for="">Contact number</label>
										    		<input type="text" class="form-control" name="number[]" value="{{ $clients->number }}" />
										    	</div>
										    </div>									   
										</div>
										<?php $count++ ?>
										@endforeach
									 <div class="row">
									 	<div class="col-md-12 col-sm-12">	
									   		
									   	</div>	
									 </div>										 
									<div class="field_wrapper"></div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>	
		<input type="hidden" id="tender_id" name="tender_id" value="{{ $tender_id }}">
		<input type="hidden" name="form_type" value="details">
		<div class="text-center" style="margin-top:20px;">
			<button class="btn btn-primary" id="submit_details" type="submit">Submit</button>
		</div>			
	</form>
	
</div>

<script>
	$(document).ready(function(){
	  alert('hello')
		$('.datepicker').datepicker({
			orientation: "bottom",
			format: "yyyy-mm-dd",
			autoclose: true,
			todayHighlight: true
		});
	});

	function add_client(){
		$(".add_client").toggleClass('d-none');
		var person_name = $('#person_val').val();
		$(".save_client, .add_client_div, .cancel_save_client").toggleClass('d-none');
	}

	function cancel_save_client(){
		$(".add_client").toggleClass('d-none');
		$(".save_client, .add_client_div, .cancel_save_client").toggleClass('d-none');
	}
	$(document).ready(function(){
	    var maxField = 10; 	    
	    var wrapper = $('.field_wrapper');
	    var x = 1; 
	    var fieldHTML = '<div class="multi_rows"><a style="color:#ffffff;margin-top:31px" class="remove_button fa fa-minus pull-right btn btn-danger"></a><div class="row remov_paren"><div class="col-md-3 col-sm-3"><div class="form-group"><label for="">Contact Name</label>	<input type="text" class="form-control" name="contact_name[]"/></div><input type="hidden" name="update_id[]" value=""></div><div class="col-md-3 col-sm-3"><div class="form-group"><label for="">Email</label><input type="text" class="form-control" name="email[]"/></div></div><div class="col-md-3 col-sm-3"><div class="form-group"><label for="">Designation</label><input type="text" class="form-control" name="desig[]"/></div></div><div class="col-md-3 col-sm-3"><div class="form-group"><label for="">Contact number</label><input type="text" class="form-control" name="number[]"/></div></div></div><div class="row"><div class="col-sm-12 col-md-12 pull-right"></div></div>'; 
	    
	    $('.add_button').click(function(){	 
	        if(x < maxField){ 
	            x++; 
	            $(wrapper).append(fieldHTML);
	            $('.multi_rows').attr('id',x)
	            $('.remove_button').attr('data-id',x)
	        }
	    });
	    
	    $(wrapper).on('click', '.remove_button', function(e){
	        e.preventDefault();
	        var id = $(this).attr('data-id');
	        $(this).parent('div').remove();
	        //$('#'+id).remove();        
	        x--;
	    });

	      $('#submit_details').on('click',function(event){
	     	event.preventDefault();
	        var form = $('#details_tab_form').serialize();
	        var tender_id = $('#tender_id').val();
	        $.ajax({
                 url: "/tender_details",
                 type: 'POST',
                 headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                 data: $('#details_tab_form').serialize(),
                 success: function (data) {
                 	$('.notify-sect').notify(data,'success');
                 	$('html,body').animate({scrollTop: 0}, 1500);
                 	window.setTimeout(function(){location.reload()},4000)
                }
	       })
	   })

	      $('.delete_reco').on('click',function(){
		      	var	id = $(this).attr('delete-id');
		      	var tender_id = $('#tender_id').val();
		      	$(this).remove();
		      	
		      	$.ajax({
	                 url: "/delete_reco",
	                 type: 'POST',
	                 headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
	                 data: {id:id,tender_id:tender_id:type:'details_delete'},
	                 success: function (data) {
	                 	if(data == 0){
	                 		location.reload()
	                 	}
	                 	else{
	                 		$('.delete_row_'+id).parent('div').remove();
	                 		$('.delete_notify').notify('Successfully Deleted','success');
	                 	}            
	                }
	      		})
	      	})
    })
</script>
